# Generated by Django 3.1.3 on 2021-05-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userr.us_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
