# Generated by Django 3.1.3 on 2021-05-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_auto_20210506_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='owner',
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='userfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
                ('v9', models.FloatField()),
                ('v10', models.FloatField()),
                ('v11', models.FloatField()),
                ('v12', models.FloatField()),
                ('v13', models.FloatField()),
                ('v14', models.FloatField()),
                ('v15', models.FloatField()),
                ('v16', models.FloatField()),
                ('v17', models.FloatField()),
                ('v18', models.FloatField()),
                ('v19', models.FloatField()),
                ('v20', models.FloatField()),
                ('v21', models.FloatField()),
                ('v22', models.FloatField()),
                ('v23', models.FloatField()),
                ('v24', models.FloatField()),
                ('v25', models.FloatField()),
                ('v26', models.FloatField()),
                ('v27', models.FloatField()),
                ('v28', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userr.us_data')),
            ],
        ),
    ]
