# Generated by Django 3.1.3 on 2021-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0003_auto_20210506_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='us_data',
            name='cardno',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='us_data',
            name='cvv',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='us_data',
            name='exp_month',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='us_data',
            name='exp_year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
