# Generated by Django 3.1.3 on 2021-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0004_auto_20210507_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
