# Generated by Django 3.2.2 on 2021-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0005_auto_20210507_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='us_data',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
